spring.application.name=spring-boot-study

app.name= My Boot App
app.max-items=50
app.admin-email=admin@example.com

spring.profiles.active=prod

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

