spring.application.name=spring-boot-study

app.name= My Boot App
app.max-items=50
app.admin-email=admin@example.com

logging.level.root=INFO
logging.level.com.example=DEBUG
logging.file.name=logs/app.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %thread %-5level %logger{36} - %msg%n

spring.profiles.active=prod

spring.jackson.serialization.write-dates-as-timestamps=false

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=Task Manager
info.app.version=1.0.0
info.app.author=Твоё Имя


